const baseDeDatosPlantas = [
    {
        id: "pasto-lloron",
        nombre: "Pasto llorón",
        cientifico: "Eragrostis curvula",
        tipo: "🌾 Gramínea",
        usos: "La ganadería como recursos forrajero de emergencias o base para crias, y la conservación ambiental, para combatir la erosión en suelos áridos y arenosos.",
        botanica: "Alta rusticidad, logevida (más de 20 años) y su excepcional capacidad para sobrevivir en ambientes aridos y semiárdos. Entre 60 cm y 120 cm de altura (alcanzando hasta 150 cm o 190 cm con las espigas florales). Crece principalmente en regiones áridas y semiáridas. Sobrevive y resiste tanto al frío extremo como al calor intenso.",
        foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Starr_050208-3897_Eragrostis_curvula.jpg/960px-Starr_050208-3897_Eragrostis_curvula.jpg",
        icono: "fa-seedling",
        colorIcono: "#d4a373"
    },
    {
        id: "agapanto",
        nombre: "Aganpanto",
        cientifico: "agapanthus africanus",
        tipo: "🌸 Ornamental",
        usos: "Por su rusticidad, follaje perenne y hermosa floración en tonos azules, violetas o blancos, Se utiliza ampliamente en exteriores: borduras y canteros, contención de suelos, macetero, flor cortada. En la medicina tradicionales africanas diversas partes de la planta se emplean para múltiples afecciones, respaldado por estudio fitoquímicos: se preparan infusiones de la raíz para aliviar la tos, resfriados y dolores en el pecho.",
        botanica: "Es una planta perenne muy popular por su resistencia y su alto valor ornamental. Se agrupan en racimos en forma de paraguas ( umbelas) que contienen entre 20 y 30 flores. Florece desde finales de primavera hasta mediados de verano en tonos azules, Violáceos o blancos. Son alargadas, planas, carnosas y brillantes. Forman densas matas que se mantienen verdes todo el año. No tienen bulbos, sino un sistema de rizomas y raíces carnosas que se agarran firmemente al suelo.",
        foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Agapanthus_africanus_in_habitat_photo_Nick_Helme_CC_by_SA.jpg/960px-Agapanthus_africanus_in_habitat_photo_Nick_Helme_CC_by_SA.jpg",
        icono: "fa-fan",
        colorIcono: "#a2d2ff"
    },
    {
        id: "lagana-de-perro",
        nombre: "Lagaña de perro",
        cientifico: "Caesalpinia gilliesii",
        tipo: "🌿 Arbusto Nativo",
        usos: "Se asocia, en la cultura popular, secreciones oculares de los canes. Tradicionalmente, sus flores se han utilizado en forma de lavajes o infusiones para tratar ciertas afecciones oculares. Sus largos estambres rojos se han empleado en el pasado como sustituto o adulterantes del azafrán debido al color amarillo que desprenden.",
        botanica: "Es una planta de crecimiento rápido, cuya floración es en verano. Posee gran resistencia a la sequia. El fruto es una legumbre o vaina aplanada y seca, cubierta de pequeños pelos, que mide 8 cm y 15 cm de longitud. Al madurar en verano, la vaina puede llegar a abrirse o \"explotar\" de forma brusca para arrojar la semilla a cierta distancia. Las hojas son de forma: compuestas y bipinnadas y de un tono verde azulado (divididas en varios pares de hojuelas mas pequeñas, parecidas a las del helecho). Miden entre 6 y 28 cm de longitud. La Lagaña es un arbusto nativo de argentina muy presente en los ambientes serranos del centro y norte del pais.",
        foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Caesalpinia_gilliesii_FlowersCloseup_15July2009_TorreLaMata.jpg/960px-Caesalpinia_gilliesii_FlowersCloseup_15July2009_TorreLaMata.jpg",
        icono: "fa-leaf",
        colorIcono: "#ffd6a5"
    },
    {
        id: "moradillo",
        nombre: "Moradillo",
        cientifico: "Schinus Fasciculados",
        tipo: "🌳 Árbol / Arbusto",
        usos: "Se usa para dolores, y también sus hojas y frutos se usan en infusiones y buches para aliviar dolores de muela, desinflamar encías, bajar la fiebre y calmar resfrios.",
        botanica: "Las hojas del moradillo son simples,alternas y brevemente pecioladas. Pueden brotar del tallo tanto solitarias como en ramillete. Tiene forma de campana o escudillo. El fruto es una pequeña drupa de 1 milímetro de diámetro, con forma de esfera. Florece en primavera. Las flores son pequeñas, blanquecinas y provistas de breves pedúnculos, se agrupan en numerosos racimos axilares. La semilla pequeña, de unos 4 milimetros de diámetro germina con facilidad sin necesidad de escarificara, basta 2 dias en remojo y luego a tierra húmeda, para que de a poco comience a emerger los primeros cotiledones.",
        foto: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Schinus_polygamus_HRM.jpg",
        icono: "fa-tree",
        colorIcono: "#ccd5ae"
    },
    {
        id: "molle-pispo",
        nombre: "Molle pispo",
        cientifico: "Schinus fasciculatu",
        tipo: "🌳 Árbol Nativo",
        usos: "En el área de Pocho y las Sierras Cordobesas, sus usos principales se centran en la herbolaria medicinal, la artesanía, las labores rurales y la gastronomia.",
        botanica: "Es un árbol de follaje perenne, lo que significan que mantienen sus hojas verdes y brillante todo el año. Por lo tanto, no pierde su follaje en invierno ni tiene una \"época de crecimiento\" donde nazcan todas sus hojas desde cero. El crecimiento de nuevas hojas y brotes ocurre de forma continua a lo largo de sus ramas, acelerándose principalmente con el aumento de las temperaturas y las lluvias durante la primavera. Es un árbol ancestral multiproposito muy valorado en la medicina tradicional y la cultura regional.",
        foto: "https://upload.wikimedia.org/wikipedia/commons/7/75/Schinus_fasciculata.jpg",
        icono: "fa-leaf",
        colorIcono: "#e9edc9"
    },
    {
        id: "tala",
        nombre: "Tala",
        cientifico: "Celtis ehrenbergiana o celtis tala renbe",
        tipo: "🌳 Árbol Nativo",
        usos: "Sus usos principales abarcan des de la medicina popular y la construcción rural, hasta su rol fundamental en el ecosistema. Sus hojas se utilizan en infusiones por sus propiedades expectorante y antiespasmódicas, ideales para aliviar la tos,el asma y otras afecciones respiratorias. También se emplea para tratar problemas digestivos y como descongestivo.",
        botanica: "Porte mediano (entre 4y12m) ,ramas desordenadas en zigzag con espinas. Gran resistencia a la sequia y su incalculable rol como refugio y alimento para la fauna local. Es un árbol de tamaño mediano, con generalmente 3 y 12 metros de altura. Su tronco suele ser retorcido, con ramificación en forma de zigzag. Posee fuertes espinas (de hasta 15 milímetros) que lo protegen de los herbívoros. Sus hojas son pequeñas ,ovaladas ,de punta aguda y bordes aserrados en primavera florece con diminutas flores verde-amarillentas. En verano y otoño produce frutos pequeños, redondos y dulce que cambian de verde a anaranjado o negro, siendo un alimento fundamental para las aves",
        foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Celtis_ehrenbergiana_arbol.jpg/960px-Celtis_ehrenbergiana_arbol.jpg",
        icono: "fa-tree",
        colorIcono: "#d4a373"
    },
    {
        id: "penca",
        nombre: "Penca",
        cientifico: "Opuntia sulfúrea",
        tipo: "🌵 Cactácea",
        usos: "Para comidas y hacer remedios caseros, por ejemplo: digestión antiinflamatoria y analgésica, diurética y depurativa .",
        botanica: "Planta rastrera capaz de formar matas, de la familia cactácea. Su altura es hasta de 60 cm. Tallos verdes, divididos en segmentos. Posee muchos tubérculos cónicos en cuyos ápices se ubican las areolas. Tiene espinas.",
        foto: "https://upload.wikimedia.org/wikipedia/commons/4/44/Opuntia_sulphurea_The_Cactaceae.jpg",
        icono: "fa-leaf",
        colorIcono: "#ccd5ae"
    },
    {
        id: "duraznillo-negro",
        nombre: "Duraznillo negro – hediondilla",
        cientifico: "Kageneckia lanceolata",
        tipo: "🌳 Árbol/Arbusto",
        usos: "tradicionalmente es solo para uso externo y remedios caseros como de forma tópica para afecciones de la piel, dolores de muelas y fiebre.",
        botanica: "crecen en zona serrana sub húmedas y semiáridas. Especie de crecimiento medio a rápido. Se reproduce fácilmente por semillas y al cabo de 10-11 meses puede llevarse a plantación, con 30 o 50 cm de altura. Las hojas del duraznillo son simples, alternas, de forma lanceolata a eliptica, color verde brillante, y desprenden un olor fuerte y desagradable al frotarlas.",
        foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Kagengekia_Lanceolata.JPG/960px-Kagengekia_Lanceolata.JPG",
        icono: "fa-leaf",
        colorIcono: "#e9edc9"
    },
    {
        id: "marcela",
        nombre: "Marcela -Vira vira",
        cientifico: "Achyrocline satureioides",
        tipo: "🌿 Arbusto",
        usos: "Es digestivo, antiespasmamódico, antinflamatorio y antiséptico.",
        botanica: "Plantas subarbustivo ramificada de 30 o 50 cm de altura. Las semillas son fotoblásticas. Se recomienda la poda hasta la base para favorecer el rebrote luego del invierno. Puede ser porpagada por división de matas, por estacas apicales de plantas jóvenes. Es un pequeño arbusto ramificado, sus hojas son alargadas y las flores son pequeñas.",
        foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Macela.JPG/960px-Macela.JPG",
        icono: "fa-seedling",
        colorIcono: "#fefae0"
    },
    {
        id: "palma",
        nombre: "Palma",
        cientifico: "Triherinax campeztris",
        tipo: "🌴 Palmera",
        usos: "Las cesteria tradicional, La construccion rural, La gastronomia y la cosmetica.",
        botanica: "Tronco recto y corona de hojas gigantes. Puede ser simple o fomar matas, A alcanzando 3 y 7 metros de altura. Esta cubierto por las vase fibrosas y espinosas de hojas viejas secas, Formando una desna capa protectora. Son risidas, En forma de abanico y de un llamativo color verde grisaseo o plateado. Termina en segmentos muy puntiagudos y punzantes.Produse grandes racimo (espadices) de flores color crema o amarilo palido. Sus frutos son pequeñas capsulas que contienen las selmillas.",
        foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Trithrinax_campestris.jpg/960px-Trithrinax_campestris.jpg",
        icono: "fa-tree",
        colorIcono: "#faedcb"
    },
    {
        id: "tola-barba-de-tigre",
        nombre: "TOLA - BARBA DE TIGRE - CORONILLA -ESPINA CRUZ",
        cientifico: "COELLETIA , SPINOSSSIMA",
        tipo: "🌿 Arbusto",
        usos: "para uso tintórea, también se puede utilizar en cercos vivos por la gran cantidad de espinas.",
        botanica: "arbusto sin hojas, de 0,4 -2m de altura y ramas espiniformes, rígidas y punzantes de color verde oliva, flores color blanco – amarillentas muy abundantes frutos maduros de color castaño – rojizo con 1-3 semillas florece desde agosto hasta febrero y los frutos maduros entre noviembre y febrero. Las hojas son pequeñas, rígidas y están cubiertas por una resina pegajosa que les da un aspecto brillante. Da frutos en finales de la primavera hasta el verano.",
        foto: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Colletia_atrox1.jpg",
        icono: "fa-leaf",
        colorIcono: "#ccd5ae"
    },
    {
        id: "polillera",
        nombre: "Polillera o gordolobo blanco",
        cientifico: "Verbascum virgatumo o vermascum blattaria",
        tipo: "🌱 Herbácea",
        usos: "Para afecciones respiratorias: se utiliza hojas y flores en infusiones o vaporizaciones por sus propiedades expectorantes, antitusígenas y emolientes. Alivian la tos seca, el asma, bronquitis y resfríos. Uso externo : las hojas hervidas se aplica en cataplasmas para reducir inflamaciones ,clamar irritaciones de la piel y tratar hemorroides o forúnculos.",
        botanica: "Puede superar los 2 metro de altura en su etapa de floración. Son grandes (de 10 a 50 de cm), de forma, ovalada y gruesas y cubiertas por una densa pelusa afelpadas que les da un tono grisáceo o planteado. Se agrupan en una espiga larga y densa. Son de un color amarillo intenso, con pétalos aterciopelados y un centro más oscuro",
        foto: "https://upload.wikimedia.org/wikipedia/commons/b/bf/Verbascum_blattaria_1.jpg",
        icono: "fa-seedling",
        colorIcono: "#fefae0"
    },
    {
        id: "siempre-verde",
        nombre: "Siempre verde",
        cientifico: "LIGUSTUM LUCIDUM",
        tipo: "🌳 Árbol/Arbusto",
        usos: "ornamentales, maderero y ambientales.",
        botanica: "Especie originaria de Asia muy común en la provincia de Córdoba el término \"siempre verde\" (o siempre verde) se utiliza para describir a los árboles o arbustos cuyas hojas no se caen durante el invierno, sino que permanecen vivas todo el año. Dependiendo de la región, suele hacer referencia a ligustro.",
        foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/FloweringLigustrumLucidumTree.jpg/960px-FloweringLigustrumLucidumTree.jpg",
        icono: "fa-tree",
        colorIcono: "#d4a373"
    },
    {
        id: "yerba-de-la-vida",
        nombre: "Yerba de la vida o quiebrarao",
        cientifico: "Heimia salicifolia",
        tipo: "🌿 Arbusto",
        usos: "Se utiliza en infusiones para aliviar dolores de estomacales , gastritis y alcalposeeoide( como la criogenina) que le otorgan propiedades alucinógenas. úlceras , actuando también como un suave laxante . Tradicionalmente se emplea para calmar los nervios , reducir el entré combatir y formental la claridad mental. Usando de forma tópica para aliviar dolores musculares y problemas en la piel. Se utiliza para aliviar la congestión , el asma y la bronquitis.",
        botanica: "Es un arbusto glabro de 50 cm a 1 metro de altura. Sus hojas son alargadas ( lanceoladas o elípticas). Similares a las del sauce. Se destaca por axilares de un color amarillo brillante.",
        foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Sinicuiche_%28Heimia_salicifolia%29_I.jpg/960px-Sinicuiche_%28Heimia_salicifolia%29_I.jpg",
        icono: "fa-leaf",
        colorIcono: "#e9edc9"
    },
    {
        id: "carqueja",
        nombre: "Carqueja",
        cientifico: "Baccharis trimera",
        tipo: "🌿 Arbusto Nativo",
        usos: "Muy eficazmente en infusión contra afecciones hepáticas y estomacales. Ademas esta preparación sirve para afecciones de la piel como heridas, úlceras, lepra y reumatismo. Espolvorizar la planta seca, sirve como secante para curar llaga sifilítica. Muy concentrada es mortalmente tóxica por ácido cianhídrico que posee.",
        botanica: "Arbusto pequeño erecto dioicio muy ramoso, ramificado desde la base. De la familia astera ceae. Su altura es de 40-50 cm. Las hojas pequeñas brácteas conspicuas. Flores blancas. Los capítulos se agrupan en el ápice de las ramas. El fruto es seco, con papos blancos siendo dispersado por el viento.",
        foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Baccharis_trimera.jpg/960px-Baccharis_trimera.jpg",
        icono: "fa-leaf",
        colorIcono: "#ccd5ae"
    },
    {
        id: "cerrajon",
        nombre: "Cerrajón camayuya lechuguilla chicoria o achicoria dulce",
        cientifico: "Sonchus oleraceus",
        tipo: "🌱 Herbácea",
        usos: "Sus hojas tiernas se comen crudas en ensaladas. Si están más desarrolladas , se cocinan igual que las acelgas o espinacas en tortillas, guisos o sopas. Con sus riqueza en potasio tiene un efecto diurético y decurativo. Tradicionalmente se usa para desintoxicar el higado, aliviar el reaumatismo y,en forma de cataplasmas para tratar infecciones o heridas en la piel.",
        botanica: "Yerba anual de 30 cm a 1 metro de altura. Tiene un tallo erguido y hueco que al cortarlo libera un látec blanquesino sus hojas son alternas y se agrupa en una roseta basal. Tiene un borde dentados y espinosos, y la vas de sus hojas superiores abrasa el tallo de forma puntiaguda sus flores de color amarillo intenso, agrupadas en capitulos florales su fruto conosido como aqueño contiene semillas con un penacho blanquesino que se dispersa fácilmente por el viento",
        foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Sonchus_February_2008-1.jpg/960px-Sonchus_February_2008-1.jpg",
        icono: "fa-leaf",
        colorIcono: "#e9edc9"
    },
    {
        id: "nabo-silvestre",
        nombre: "Nabo silvestre, yuyo, naba o naviza,nabillo.",
        cientifico: "Brassica rapa",
        tipo: "🌱 Herbácea",
        usos: "Toda la planta es comestible; se recolecta en el campo y se consume en ensaladas , salteados o hervida , similar a la acelga.",
        botanica: "Alcanza entre 30 y 150 cm de altura, se caracteriza por sus llamativas flores amarillas de cuatro pétalos en forma de cruz. Todas sus partes tiernas (hojas,tallos y flores) son comestibles. Es valorado por sus usos culinarios,medicinales y ecológicos.",
        foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Brassica_rapa_plant.jpg/960px-Brassica_rapa_plant.jpg",
        icono: "fa-seedling",
        colorIcono: "#fefae0"
    },
    {
        id: "chanar",
        nombre: "CHAÑAR - CHICAL",
        cientifico: "GEOFFROEA , DECORTICANS",
        tipo: "🌳 Árbol Nativo",
        usos: "muy resistente a los vientos por lo que es recomendado para veredas jardines, plaza, riveras, cercos, forrajera, tintórea, medicinal, comestible.",
        botanica: "Árbol mediano, espinoso alcanza 6 y 10 metros, sus flores son amarillas y perfumadas agrupadas en inflorescencias. Es un árbol nativo del monte criollo (presente en el departamento Pocho y toda la provincia Córdoba). Es fundamental para el ecosistema y la medicina tradicional gracias a su corteza fotosintéticas, sus raíces invasivas y sus frutos dulces comestibles.",
        foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Geoffroea_decorticans_1a.jpg/960px-Geoffroea_decorticans_1a.jpg",
        icono: "fa-tree",
        colorIcono: "#d4a373"
    },
    {
        id: "cabello-de-angel",
        nombre: "Cabello de ángel - Barba de viejo.",
        cientifico: "Clematis montevidensis",
        tipo: "🌿 Enredadera Parásita",
        usos: "En dósis muy bajas puede ser usado como diurético y para problemas de piel. Es irritante asi que hoy casi no se recomienda sin guía ya que puede irritar boca y estómago.Las hojas se usan en cataplasmas como antineurálgicas. También se usa para artesanias, decoraciones y la utilizan los pájaros para hacer sus nidos.",
        botanica: "Florece en primavera y verano y fructífica en verano y otoño . Multiplicación por semillas, estacas y acodos . Es una enredareda parásita sin hojas ni clorofila . Sus tallos son hilos finos y dorados que se enrollan alrededor de otras plantas ,extrayendo agua y nutrientes mediante estructuras llamadas hautorios. Carece de raíces verdaderas y hojas funcionales. Sus tallos son filamentos muy delgados de color amarillo, naranja o rojizo que forman marañas densas.",
        foto: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Clematis_montevidensis_1.jpg",
        icono: "fa-leaf",
        colorIcono: "#faedcb"
    },
    {
        id: "menta-poleo",
        nombre: "Menta poleo,poleo menta,poleo.",
        cientifico: "Mentha pulegium.",
        tipo: "🌱 Herbácea",
        usos: "Se usa principalmente en infusiones o como hierba para el mate. Destacada por sus propiedades digestivas, carminativas (reduce gases) y expectorantes. Sin embargo se debe consumir con mucha precaución por su toxicidad hepática.",
        botanica: "Es una hierba aromática perenne de la familia de las lamiáceas. Es ampliamente conocida por sus hojas pequeñas ovaladas, tallos cuadrangulares, flores violáceas y su intenso aroma. Se utiliza principalmente en infusiones por sus beneficios digestivos y calmantes.",
        foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Gardenology.org-IMG_2751_rbgs11jan.jpg/960px-Gardenology.org-IMG_2751_rbgs11jan.jpg",
        icono: "fa-seedling",
        colorIcono: "#ccd5ae"
    }
];